import React, { createContext, useState, useContext } from "react";

export const LanguageContext = createContext();

export const supportedLanguages = [
  { code: "ta", name: "தமிழ்" },
  { code: "hi", name: "हिंदी" },
  { code: "en", name: "English" },
];

// Complete translations object
const translations = {
  en: {
    home: 'Home',
    about: 'About Us',
    services: 'Services',
    gallery: 'Gallery',
    events: 'Events',
    contact: 'Contact',
    heroTitle1: 'Welcome to Nallor Vattam',
    heroTitle2: 'For Social Development',
    heroTitle3: 'Preserving Tradition',
    heroSubtitle1: 'Working for the growth and progress of our community',
    heroSubtitle2: 'Education, health and social development programs',
    heroSubtitle3: 'Protecting our culture and heritage',
    learnMore: 'Learn More',
    getInvolved: 'Join with us',
    aboutTitle: 'About Nallor Vattam',
    aboutText1: 'Nallor Vattam is a community organization dedicated to the social, cultural, and economic development of our region.',
    aboutText2: 'Our mission is to create sustainable growth opportunities through education, healthcare initiatives, and cultural preservation programs.',
    aboutText3: 'Nallore Vattam is a community organization dedicated to promoting and preserving the cultural heritage of our region. Founded in 2005, we have been bringing together people from various backgrounds to celebrate our shared traditions, values, and heritage.',
    servicesTitle: 'Our Services',
    service1: 'Student Domain',
    service2: 'Village Domain',
    service3: 'Domain of Biology',
    service4: 'Government Domain',
    service5: 'Settings Domain',
    service6: 'Womens Domain',
    service7: 'Youth Domain',
    service8: 'World Domain',
    service9: 'Environmental Domain',
    service10: 'Awareness Domain',
    galleryTitle: 'Our Gallery',
    eventsTitle: 'Upcoming Events',
    event1: 'Cultural Festival - Jan 15, 2024',
    event2: 'Health Camp - Feb 20, 2024',
    event3: 'Educational Workshop - Mar 10, 2024',
    contactTitle: 'Contact Us',
    name: 'Your Name',
    email: 'Your Email',
    message: 'Your Message',
    send: 'Send Message',
    footerDescription: 'Nallore Vattam is an organization working for social development and cultural preservation.',
    quickLinks: 'Quick Links',
    contactInfo: 'Contact Information',
    address: 'Periyaar pathai, Choolaimedu, Chennai-600094, Tamil Nadu, India',
    phone: '+91 98765 43210',
    emailAddress: 'info@nallorevattam.com',
    allRightsReserved: 'All Rights Reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    projectName: 'Nallor Vattam',
    photoGallery: 'Photo Gallery',
    gallerySubtitle: 'Visual stories of our community\'s journey, achievements, and celebrations',
    allPhotos: 'All Photos',
    culturalEvents: 'Cultural Events',
    education: 'Education',
    healthCamps: 'Health Camps',
    community: 'Community',
    sendMessage: 'Send us a Message',
    phoneNumber: 'Phone Number',
    subject: 'Subject',
    getInTouch: 'Get in Touch',
    ourAddress: 'Our Address',
    workingHours: 'Working Hours',
    followUs: 'Follow Us',
    contactSubtitle: 'We\'d love to hear from you. Get in touch and let\'s start a conversation.',
    aboutNalloreVattam: 'About Nallor Vattam',
    aboutSubtitle: 'Building a stronger community through unity and development',
    ourMission: 'Our Mission',
    ourVision: 'Our Vision',
     president: "President",
  secretary: "Secretary", 
  treasurer: "Treasurer",
  presidentDesc: "Leading community initiatives for over 10 years",
  secretaryDesc: "Dedicated to women empowerment programs",
  treasurerDesc: "Financial management and resource allocation",
    ourJourney: 'Our Journey',
    ourLeadershipTeam: 'Our Leadership Team',
    ourServices: 'Our Services',
    servicesSubtitle: 'Comprehensive community development programs designed to empower and transform lives',
    keyFeatures: 'Key Features',
    howItWorks: 'How It Works',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    register: 'Register',
    apply: 'Apply',
    review: 'Review',
    participate: 'Participate',
    learnMoreBtn: 'Learn More',
    applyNow: 'Apply Now',
    createAccount: 'Create your account and complete profile',
    chooseService: 'Choose service and submit application',
    teamReview: 'Our team reviews your application',
    joinProgram: 'Join the program and get benefits',
    faq1Question: 'How can I apply for education scholarships?',
    faq1Answer: 'Applications are accepted annually in May. Visit our office or website for application forms and eligibility criteria.',
    faq2Question: 'Are health camps completely free?',
    faq2Answer: 'Yes, all our health camps provide free medical checkups, basic medicines, and health consultations.',
    faq3Question: 'Do I need prior experience for skill development programs?',
    faq3Answer: 'No prior experience is required. Our programs are designed for beginners and include basic to advanced training.',
    faq4Question: 'What documents are required for registration?',
    faq4Answer: 'You need identity proof, address proof, and relevant educational or professional certificates based on the service you are applying for.',
    faq5Question: 'How long does the application process take?',
    faq5Answer: 'The application review typically takes 2-3 weeks. You will be notified via email or phone once your application is processed.',
    studentDomain: 'Student Domain',
    villageDomain: 'Village Domain',
    domainOfBiology: 'Domain of Biology',
    governmentDomain: 'Government Domain',
    settingsDomain: 'Settings Domain',
    womensDomain: 'Womens Domain',
    youthDomain: 'Youth Domain',
    worldDomain: 'World Domain',
    environmentalDomain: 'Environmental Domain',
    awarenessDomain: 'Awareness Domain',
    studentDomainDesc: 'Comprehensive educational support and development programs for students. Career guidance, scholarships, and skill enhancement initiatives.',
    villageDomainDesc: 'Community development and rural welfare programs for village improvement. Infrastructure development and social service initiatives.',
    domainOfBiologyDesc: 'Biological research and agricultural development for sustainable farming. Environmental studies and biodiversity conservation programs.',
    governmentDomainDesc: 'Coordination with government authorities for public welfare services. Policy implementation and civic engagement activities.',
    settingsDomainDesc: 'Technical configuration and program management for organizational operations. System support and resource coordination services.',
    womensDomainDesc: 'Empowerment programs and support services for women development. Self-help groups, health awareness, and economic independence initiatives.',
    youthDomainDesc: 'Youth development programs and leadership training for young individuals. Career guidance, sports, and talent development activities.',
    worldDomainDesc: 'Global partnerships and international collaboration for community development. Cultural exchange and knowledge sharing programs.',
    environmentalDomainDesc: 'Environmental protection and sustainability initiatives for green living. Clean energy, waste management, and conservation programs.',
    awarenessDomainDesc: 'Public awareness campaigns and educational programs for community enlightenment. Social media outreach and workshop initiatives.',
    educationalSupport: 'Educational Support',
    careerCounseling: 'Career Counseling',
           organizationFounded: "Organization Founded",
  firstCommunityCenter: "First Community Center",
  educationProgramLaunch: "Education Program Launch",
  digitalTransformation: "Digital Transformation",
  members500: "500+ Members",
  startedWith50Members: "Started with 50 members",
  establishedPermanentSpace: "Established permanent space",
  scholarshipsForStudents: "Scholarships for students",
  onlineCommunityPlatform: "Online community platform",
  communityGrowthMilestone: "Community growth milestone",
    scholarshipPrograms: 'Scholarship Programs',
    skillDevelopment: 'Skill Development',
    communityDevelopment: 'Community Development',
    infrastructure: 'Infrastructure',
    ruralWelfare: 'Rural Welfare',
    socialServices: 'Social Services',
    agriculturalResearch: 'Agricultural Research',
    environmentalStudies: 'Environmental Studies',
    biodiversity: 'Biodiversity',
    sustainableFarming: 'Sustainable Farming',
    publicServices: 'Public Services',
    policyImplementation: 'Policy Implementation',
    civicEngagement: 'Civic Engagement',
    communityOutreach: 'Community Outreach',
    systemConfiguration: 'System Configuration',
    technicalSupport: 'Technical Support',
    programManagement: 'Program Management',
    resourceCoordination: 'Resource Coordination',
    womensEmpowerment: 'Womens Empowerment',
    selfHelpGroups: 'Self-Help Groups',
    healthAwareness: 'Health Awareness',
    economicIndependence: 'Economic Independence',
    youthLeadership: 'Youth Leadership',
    sportsActivities: 'Sports Activities',
    talentDevelopment: 'Talent Development',
    globalPartnerships: 'Global Partnerships',
    culturalExchange: 'Cultural Exchange',
    internationalProjects: 'International Projects',
    knowledgeSharing: 'Knowledge Sharing',
    environmentalProtection: 'Environmental Protection',
    cleanEnergy: 'Clean Energy',
     youtubeTitle: "Our YouTube Channel",
  youtubeDescription: "Watch our latest videos and stay updated with our community activities",
  contactUs: "Contact Us",

    wasteManagement: 'Waste Management',
    greenInitiatives: 'Green Initiatives',
    publicAwareness: 'Public Awareness',
    educationalCampaigns: 'Educational Campaigns',
    socialMediaOutreach: 'Social Media Outreach',
    communityWorkshops: 'Community Workshops',
    academicYear: 'Academic Year',
    continuous: 'Continuous',
    studentsAllAges: 'Students All Ages',
    allVillagers: 'All Villagers',
    farmersResearchers: 'Farmers & Researchers',
    allCitizens: 'All Citizens',
    authorizedPersonnel: 'Authorized Personnel',
    womenAllAges: 'Women All Ages',
    youth15_30: 'Youth 15-30 Years',
    allMembers: 'All Members',
    allCommunityMembers: 'All Community Members',
    generalPublic: 'General Public',
    missionDescription: 'To empower our community through education, cultural preservation, and sustainable development initiatives that create lasting positive impact.',
    visionDescription: 'A self-reliant, culturally rich community where every member has access to opportunities for growth, education, and prosperity.',
    tuitionFeeSupport: 'Tuition Fee Support',
    bookAllowance: 'Book Allowance',
    mentorshipProgram: 'Mentorship Program',
    careerGuidance: 'Career Guidance',
    generalCheckup: 'General Checkup',
    dentalCare: 'Dental Care',
    eyeTesting: 'Eye Testing',
    healthAwareness: 'Health Awareness',
    organicFarming: 'Organic Farming',
    waterManagement: 'Water Management',
    cropRotation: 'Crop Rotation',
    marketLinkages: 'Market Linkages',
    festivalCelebrations: 'Festival Celebrations',
    traditionalArts: 'Traditional Arts',
    musicDance: 'Music & Dance',
    heritageWorkshops: 'Heritage Workshops',
    computerSkills: 'Computer Skills',
    handicrafts: 'Handicrafts',
    technicalTraining: 'Technical Training',
    softSkills: 'Soft Skills',
    businessTraining: 'Business Training',
    legalAwareness: 'Legal Awareness',
    healthPrograms: 'Health Programs',
    annual: 'Annual',
    quarterly: 'Quarterly',
    seasonal: 'Seasonal',
    monthly: 'Monthly',
    ongoing: 'Ongoing',
    months3_6: '3-6 Months',
    studentsAged16_25: 'Students aged 16-25',
    farmersAgriEnthusiasts: 'Farmers & Agri-enthusiasts',
    allAgeGroups: 'All age groups',
    youthAdults: 'Youth & Adults',
    womenGirls: 'Women & Girls',
    extracurricular: 'Extracurricular Activities',
    personalityDevelopment: 'Personality Development',
    sanitation: 'Sanitation',
    welfarePrograms: 'Welfare Programs',
    environmentalConservation: 'Environmental Conservation',
    soilTesting: 'Soil Testing',
    ecologicalBalance: 'Ecological Balance',
    publicService: 'Public Service',
    communityWelfare: 'Community Welfare',
    exploreDomain: 'Explore Domain',
    readMoreAboutUs: 'Read More About Us',
    traditionalDance: 'Traditional Dance Performance',
    studentScholarship: 'Student Scholarship Distribution',
    freeHealthCheckup: 'Free Health Checkup Camp',
    communityMeeting: 'Community Meeting',
    festivalCelebration: 'Festival Celebration',
    computerTraining: 'Computer Training Session',
    youthSports: 'Youth Sports Event',
    musicProgram: 'Music Program',
    libraryInauguration: 'Library Inauguration',
    cleanlinessDrive: 'Cleanliness Drive',
    interactiveMap: 'Interactive Map',
    thankYouMessage: 'Thank you for your message! We\'ll get back to you soon.',
    mapPlaceholder: 'Map integration would go here',
    exploreServices: 'Explore Services',
    exploreGallery: 'Explore Gallery',
        learnMoreAboutUs: "Learn More About Us",
        contactDescription: "Get in touch with us. We're here to help and answer any questions you might have.",
      title: 'Our YouTube Channel',
      description: 'Watch our latest videos and stay updated with our community activities',
      allVideos: 'All Videos',
      latest: 'Latest',
      mostViewed: 'Most Viewed',
      events: 'Events',
      new: 'NEW',
      share: 'Share',
      like: 'Like',
      subscribers: 'Subscribers',
      videos: 'Videos',
      views: 'Views',
      years: 'Years Creating',
      ctaTitle: 'Subscribe to Our YouTube Channel',
      ctaDescription: 'Stay updated with our latest community activities, events, and educational content',
      subscribeNow: 'Subscribe Now',
      loadMore: 'Load More Videos',
       exploreInitiatives: "Explore our initiatives in",
    exploreDomain: "Explore Domain",
    readMoreAboutUs: "Read More About Us",
  viewAllServices: "View All Services",
      viewFullGallery: "View Full Gallery",
        galleryDescription: "Capturing moments of community growth, cultural celebrations, and meaningful interactions"


  },
  ta: {
    home: 'முகப்பு',
    about: 'எங்களைப் பற்றி',
    services: 'சேவைகள்',
    gallery: 'கேலரி',
    events: 'நிகழ்வுகள்',
    contact: 'தொடர்பு கொள்ள',
    heroTitle1: 'நல்லூர் வட்டத்திற்கு வரவேற்கிறோம்',
    heroTitle2: 'சமூக மேம்பாட்டுக்காக',
    heroTitle3: 'பாரம்பரியத்தைப் பாதுகாத்தல்',
    heroSubtitle1: 'எங்கள் சமூகத்தின் வளர்ச்சி மற்றும் முன்னேற்றத்திற்காக பணியாற்றுகிறோம்',
    heroSubtitle2: 'கல்வி, ஆரோக்கியம் மற்றும் சமூக மேம்பாட்டுத் திட்டங்கள்',
    heroSubtitle3: 'எங்கள் கலாச்சாரம் மற்றும் பாரம்பரியத்தைப் பாதுகாத்தல்',
    learnMore: 'மேலும் அறிக',
    getInvolved: 'எங்களுடன் இணைக',
    aboutTitle: 'நல்லூர் வட்டம் பற்றி',
    aboutText1: 'நல்லூர் வட்டம் என்பது எங்கள் பகுதியின் சமூக, கலாச்சார மற்றும் பொருளாதார மேம்பாட்டிற்காக அர்ப்பணிக்கப்பட்ட ஒரு சமூக அமைப்பாகும்.',
    aboutText2: 'கல்வி, ஆரோக்கியப் பராமரிப்பு முன்முயற்சிகள் மற்றும் கலாச்சாரப் பாதுகாப்புத் திட்டங்கள் மூலம் நிலையான வளர்ச்சி வாய்ப்புகளை உருவாக்குவதே எங்கள் நோக்கம்.',
    aboutText3: 'நல்லூர் வட்டம் என்பது எங்கள் பகுதியின் கலாச்சார மரபுகளை மேம்படுத்துவதற்கும் பாதுகாப்பதற்கும் அர்ப்பணிக்கப்பட்ட ஒரு சமூக அமைப்பாகும். 2005 ஆம் ஆண்டில் நிறுவப்பட்டது, பல்வேறு பின்னணியிலிருந்து வந்த மக்களை ஒன்றிணைத்து எங்கள் பகிரப்பட்ட பாரம்பரியங்கள், மதிப்புகள் மற்றும் மரபுகளைக் கொண்டாடுகிறோம்.',
    servicesTitle: 'எங்கள் சேவைகள்',
    service1: 'மாணவர் களம்',
    service2: 'கிராமக் களம்',
    service3: 'உயிரியல் களம்',
    service4: 'அரசு களம்',
    service5: 'அமைப்புகள் களம்',
    service6: 'பெண்கள் களம்',
    service7: 'இளைஞர் களம்',
    service8: 'உலகக் களம்',
    service9: 'சுற்றுச்சூழல் களம்',
    service10: 'விழிப்புணர்வு களம்',
    galleryTitle: 'எங்கள் கேலரி',
    eventsTitle: 'வரவிருக்கும் நிகழ்வுகள்',
    event1: 'கலாச்சார திருவிழா - ஜனவரி 15, 2024',
    event2: 'ஆரோக்கிய முகாம் - பிப்ரவரி 20, 2024',
    event3: 'கல்வி பணிப்பட்டறை - மார்ச் 10, 2024',
    contactTitle: 'எங்களைத் தொடர்பு கொள்ள',
    name: 'உங்கள் பெயர்',
    email: 'உங்கள் மின்னஞ்சல்',
    message: 'உங்கள் செய்தி',
    send: 'செய்தியை அனுப்புக',
    footerDescription: 'நல்லூர் வட்டம் என்பது சமூக மேம்பாடு மற்றும் கலாச்சாரப் பாதுகாப்புக்காக பணியாற்றும் ஒரு அமைப்பாகும்.',
    quickLinks: 'விரைவு இணைப்புகள்',
    contactInfo: 'தொடர்பு தகவல்',
    address: 'பெரியார் பாதை, சூளைமேடு, சென்னை-600094, தமிழ்நாடு, இந்தியா',
    phone: '+91 98765 43210',
    emailAddress: 'info@nallorevattam.com',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    projectName: 'நல்லூர் வட்டம்',
    photoGallery: 'புகைப்பட கேலரி',
    gallerySubtitle: 'எங்கள் சமூகத்தின் பயணம், சாதனைகள் மற்றும் கொண்டாட்டங்களின் காட்சிக் கதைகள்',
    allPhotos: 'அனைத்து புகைப்படங்கள்',
    culturalEvents: 'கலாச்சார நிகழ்வுகள்',
    education: 'கல்வி',
    healthCamps: 'ஆரோக்கிய முகாம்கள்',
    community: 'சமூகம்',
    sendMessage: 'எங்களுக்கு ஒரு செய்தியை அனுப்புங்கள்',
    phoneNumber: 'தொலைபேசி எண்',
    subject: 'தலைப்பு',
    getInTouch: 'தொடர்பு கொள்ளுங்கள்',
    ourAddress: 'எங்கள் முகவரி',
    workingHours: 'பணி நேரங்கள்',
    followUs: 'எங்களைப் பின்தொடருங்கள்',
    contactSubtitle: 'உங்களிடமிருந்து கேட்பதில் நாங்கள் மகிழ்ச்சியடைகிறோம். தொடர்பு கொண்டு ஒரு உரையாடலைத் தொடங்குவோம்.',
    aboutNalloreVattam: 'நல்லூர் வட்டம் பற்றி',
    aboutSubtitle: 'ஒற்றுமை மற்றும் மேம்பாட்டின் மூலம் வலுவான சமூகத்தை உருவாக்குதல்',
    ourMission: 'எங்கள் நோக்கம்',
    ourVision: 'எங்கள் பார்வை',
    ourJourney: 'எங்கள் பயணம்',
    ourLeadershipTeam: 'எங்கள் தலைமைக் குழு',
    ourServices: 'எங்கள் சேவைகள்',
    servicesSubtitle: 'சமூக மேம்பாட்டுத் திட்டங்கள்',
    keyFeatures: 'முக்கிய அம்சங்கள்',
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
     president: "தலைவர்",
  secretary: "செயலாளர்",
  treasurer: "பொருளாளர்", 
  presidentDesc: "10 ஆண்டுகளுக்கும் மேலாக சமூக முன்முயற்சிகளை வழிநடத்துகிறார்",
  secretaryDesc: "மகளிர் அதிகாரமளிப்பு திட்டங்களுக்காக அர்ப்பணிக்கப்பட்டவர்",
  treasurerDesc: "நிதி மேலாண்மை மற்றும் வள ஒதுக்கீடு",
    frequentlyAskedQuestions: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    register: 'பதிவு செய்க',
    apply: 'விண்ணப்பிக்கவும்',
    review: 'மதிப்பாய்வு',
    participate: 'பங்கேற்கவும்',
    learnMoreBtn: 'மேலும் அறிக',
    applyNow: 'இப்போதே விண்ணப்பிக்கவும்',
    createAccount: 'உங்கள் கணக்கை உருவாக்கவும்',
    chooseService: 'சேவையைத் தேர்ந்தெடுத்து விண்ணப்பிக்கவும்',
    teamReview: 'எங்கள் குழு உங்கள் விண்ணப்பத்தை மதிப்பாய்வு செய்கிறது',
    joinProgram: 'திட்டத்தில் சேர்ந்து பயன்களைப் பெறுங்கள்',
    faq1Question: 'கல்வி உதவித்தொகைக்கு எவ்வாறு விண்ணப்பிக்கலாம்?',
    faq1Answer: 'விண்ணப்பங்கள் ஆண்டுதோறும் மே மாதத்தில் ஏற்றுக்கொள்ளப்படும். விண்ணப்ப படிவங்கள் மற்றும் தகுதி விதிமுறைகளுக்கு எங்கள் அலுவலகம் அல்லது வலைத்தளத்தைப் பார்வையிடவும்.',
    faq2Question: 'ஆரோக்கிய முகாம்கள் முற்றிலும் இலவசமானதா?',
    faq2Answer: 'ஆம், எங்கள் அனைத்து ஆரோக்கிய முகாம்களும் இலவச மருத்துவ பரிசோதனைகள், அடிப்படை மருந்துகள் மற்றும் ஆரோக்கிய ஆலோசனைகளை வழங்குகின்றன.',
    faq3Question: 'திறன் மேம்பாட்டுத் திட்டங்களுக்கு முன் அனுபவம் தேவையா?',
    faq3Answer: 'முன் அனுபவம் தேவையில்லை. எங்கள் திட்டங்கள் ஆரம்பநிலையினருக்காக வடிவமைக்கப்பட்டுள்ளன மற்றும் அடிப்படை முதல் மேம்பட்ட பயிற்சியை உள்ளடக்கியது.',
    faq4Question: 'பதிவு செய்வதற்கு என்ன ஆவணங்கள் தேவை?',
    faq4Answer: 'அடையாள சான்று, முகவரி சான்று மற்றும் நீங்கள் விண்ணப்பிக்கும் சேவையின் அடிப்படையில் தொடர்புடைய கல்வி அல்லது தொழில்முறை சான்றிதழ்கள் தேவை.',
    faq5Question: 'விண்ணப்ப செயல்முறை எவ்வளவு நேரம் எடுக்கும்?',
    faq5Answer: 'விண்ணப்ப மதிப்பாய்வு பொதுவாக 2-3 வாரங்கள் எடுக்கும். உங்கள் விண்ணப்பம் செயல்படுத்தப்பட்டதும் மின்னஞ்சல் அல்லது தொலைபேசி மூலம் அறிவிக்கப்படுவீர்கள்.',
    studentDomain: 'மாணவர் களம்',
    villageDomain: 'கிராமக் களம்',
    domainOfBiology: 'உயிரியல் களம்',
    governmentDomain: 'அரசு களம்',
    settingsDomain: 'அமைப்புகள் களம்',
    womensDomain: 'பெண்கள் களம்',
    youthDomain: 'இளைஞர் களம்',
    worldDomain: 'உலகக் களம்',
    environmentalDomain: 'சுற்றுச்சூழல் களம்',
    awarenessDomain: 'விழிப்புணர்வு களம்',
    studentDomainDesc: 'மாணவர்களுக்கான விரிவான கல்வி ஆதரவு மற்றும் மேம்பாட்டுத் திட்டங்கள். தொழில் வழிகாட்டுதல், உதவித்தொகைகள் மற்றும் திறன் மேம்பாட்டு முன்முயற்சிகள்.',
    villageDomainDesc: 'கிராம மேம்பாட்டிற்கான சமூக மேம்பாடு மற்றும் கிராமப்புற நலன்புரி திட்டங்கள். உள்கட்டமைப்பு மேம்பாடு மற்றும் சமூக சேவை முன்முயற்சிகள்.',
    domainOfBiologyDesc: 'நிலையான விவசாயத்திற்கான உயிரியல் ஆராய்ச்சி மற்றும் விவசாய மேம்பாடு. சுற்றுச்சூழல் ஆய்வுகள் மற்றும் உயிரியல் பல்வகைமைப் பாதுகாப்புத் திட்டங்கள்.',
    governmentDomainDesc: 'பொது நலன் சேவைகளுக்கான அரசு அதிகாரிகளுடன் ஒருங்கிணைப்பு. கொள்கை செயல்படுத்தல் மற்றும் குடிமக்கள் ஈடுபாட்டு நடவடிக்கைகள்.',
    settingsDomainDesc: 'நிறுவன செயல்பாடுகளுக்கான தொழில்நுட்ப கட்டமைப்பு மற்றும் திட்ட மேலாண்மை. கணினி ஆதரவு மற்றும் வள ஒருங்கிணைப்பு சேவைகள்.',
    womensDomainDesc: 'பெண்கள் மேம்பாட்டிற்கான மேம்பாட்டுத் திட்டங்கள் மற்றும் ஆதரவு சேவைகள். சுயஉதவிக் குழுக்கள், ஆரோக்கிய விழிப்புணர்வு மற்றும் பொருளாதார சுதந்திர முன்முயற்சிகள்.',
    youthDomainDesc: 'இளைஞர்களுக்கான இளைஞர் மேம்பாட்டுத் திட்டங்கள் மற்றும் தலைமைப் பயிற்சி. தொழில் வழிகாட்டுதல், விளையாட்டுகள் மற்றும் திறன் மேம்பாட்டு நடவடிக்கைகள்.',
    worldDomainDesc: 'சமூக மேம்பாட்டிற்கான உலகளாவிய கூட்டுப்பணிகள் மற்றும் சர்வதேச ஒத்துழைப்பு. கலாச்சார பரிமாற்றம் மற்றும் அறிவுப் பகிர்வுத் திட்டங்கள்.',
    environmentalDomainDesc: 'பசுமை வாழ்க்கைக்கான சுற்றுச்சூழல் பாதுகாப்பு மற்றும் நிலைத்தன்மை முன்முயற்சிகள். தூய்மையான ஆற்றல், கழிவு மேலாண்மை மற்றும் பாதுகாப்புத் திட்டங்கள்.',
    awarenessDomainDesc: 'சமூக அறிவொளிக்கான பொது விழிப்புணர்வு பிரச்சாரங்கள் மற்றும் கல்வித் திட்டங்கள். சமூக ஊடக வெளிப்பாடு மற்றும் பணிப்பட்டறை முன்முயற்சிகள்.',
    educationalSupport: 'கல்வி ஆதரவு',
      contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்",
    careerCounseling: 'தொழில் வழிகாட்டுதல்',
    scholarshipPrograms: 'உதவித்தொகைத் திட்டங்கள்',
    skillDevelopment: 'திறன் மேம்பாடு',
    communityDevelopment: 'சமூக மேம்பாடு',
    infrastructure: 'உள்கட்டமைப்பு',
    ruralWelfare: 'கிராமப்புற நலன்',
    socialServices: 'சமூக சேவைகள்',
    agriculturalResearch: 'விவசாய ஆராய்ச்சி',
    environmentalStudies: 'சுற்றுச்சூழல் ஆய்வுகள்',
    biodiversity: 'உயிரியல் பல்வகைமை',
    sustainableFarming: 'நிலையான விவசாயம்',
    publicServices: 'பொது சேவைகள்',
    policyImplementation: 'கொள்கை செயல்படுத்தல்',
    civicEngagement: 'குடிமக்கள் ஈடுபாடு',
    communityOutreach: 'சமூக வெளிப்பாடு',
    systemConfiguration: 'கணினி கட்டமைப்பு',
    technicalSupport: 'தொழில்நுட்ப ஆதரவு',
    programManagement: 'திட்ட மேலாண்மை',
    resourceCoordination: 'வள ஒருங்கிணைப்பு',
    womensEmpowerment: 'பெண்கள் மேம்பாடு',
    selfHelpGroups: 'சுயஉதவிக் குழுக்கள்',
    healthAwareness: 'ஆரோக்கிய விழிப்புணர்வு',
    economicIndependence: 'பொருளாதார சுதந்திரம்',
    youthLeadership: 'இளைஞர் தலைமை',
    sportsActivities: 'விளையாட்டு நடவடிக்கைகள்',
    talentDevelopment: 'திறன் மேம்பாடு',
    globalPartnerships: 'உலகளாவிய கூட்டுப்பணிகள்',
    culturalExchange: 'கலாச்சார பரிமாற்றம்',
    internationalProjects: 'சர்வதேச திட்டங்கள்',
    knowledgeSharing: 'அறிவுப் பகிர்வு',
    environmentalProtection: 'சுற்றுச்சூழல் பாதுகாப்பு',
    cleanEnergy: 'தூய்மையான ஆற்றல்',
    wasteManagement: 'கழிவு மேலாண்மை',
    greenInitiatives: 'பசுமை முன்முயற்சிகள்',
    publicAwareness: 'பொது விழிப்புணர்வு',
    educationalCampaigns: 'கல்விப் பிரச்சாரங்கள்',
    socialMediaOutreach: 'சமூக ஊடக வெளிப்பாடு',
    communityWorkshops: 'சமூக பணிப்பட்டறைகள்',
    academicYear: 'கல்வி ஆண்டு',
    continuous: 'தொடர்ச்சியான',
    studentsAllAges: 'அனைத்து வயது மாணவர்கள்',
    allVillagers: 'அனைத்து கிராமவாசிகள்',
    farmersResearchers: 'விவசாயிகள் & ஆராய்ச்சியாளர்கள்',
    allCitizens: 'அனைத்து குடிமக்கள்',
    authorizedPersonnel: 'அங்கீகரிக்கப்பட்ட பணியாளர்கள்',
    womenAllAges: 'அனைத்து வயது பெண்கள்',
    youth15_30: 'இளைஞர்கள் 15-30 வயது',
    allMembers: 'அனைத்து உறுப்பினர்கள்',
    allCommunityMembers: 'அனைத்து சமூக உறுப்பினர்கள்',
    generalPublic: 'பொது மக்கள்',
    missionDescription: 'கல்வி, கலாச்சாரப் பாதுகாப்பு மற்றும் நிலையான மேம்பாட்டு முன்முயற்சிகள் மூலம் எங்கள் சமூகத்தை மேம்படுத்துவதே எங்கள் நோக்கம்.',
    visionDescription: 'ஒவ்வொரு உறுப்பினருக்கும் வளர்ச்சி, கல்வி மற்றும் செழிப்புக்கான வாய்ப்புகள் உள்ள சுயநம்பிக்கை உள்ள, கலாச்சார ரீதியாக செழிப்பான சமூகம்.',
    tuitionFeeSupport: 'கல்விக் கட்டண ஆதரவு',
    bookAllowance: 'புத்தகப்படி',
    mentorshipProgram: 'வழிகாட்டுதல் திட்டம்',
    careerGuidance: 'தொழில் வழிகாட்டுதல்',
    generalCheckup: 'பொது பரிசோதனை',
    dentalCare: 'பல் பராமரிப்பு',
    eyeTesting: 'கண் பரிசோதனை',
    healthAwareness: 'ஆரோக்கிய விழிப்புணர்வு',
    organicFarming: 'கரிம விவசாயம்',
    waterManagement: 'நீர் மேலாண்மை',
    cropRotation: 'பயிர் சுழற்சி',
        learnMoreAboutUs: "எங்களைப் பற்றி மேலும் அறிக",
      viewAllServices: "அனைத்து சேவைகளையும் காண்க",
  galleryDescription: "சமூக வளர்ச்சி, கலாச்சார விழாக்கள் மற்றும் அர்த்தமுள்ள தொடர்புகளின் கணங்களைப் பதிவு செய்தல்",
    marketLinkages: 'சந்தை இணைப்புகள்',
    festivalCelebrations: 'திருவிழா கொண்டாட்டங்கள்',
    traditionalArts: 'பாரம்பரிய கலைகள்',
    musicDance: 'இசை & நடனம்',
    heritageWorkshops: 'மரபு பணிப்பட்டறைகள்',
    computerSkills: 'கணினி திறன்கள்',
    handicrafts: 'கைவினைப்பொருட்கள்',
    technicalTraining: 'தொழில்நுட்ப பயிற்சி',
    softSkills: 'மென்திறன்கள்',
    businessTraining: 'வணிக பயிற்சி',
    legalAwareness: 'சட்ட விழிப்புணர்வு',
    healthPrograms: 'ஆரோக்கியத் திட்டங்கள்',
    annual: 'ஆண்டுதோறும்',
    quarterly: 'காலாண்டுதோறும்',
    seasonal: 'பருவகால',
    monthly: 'மாதந்தோறும்',
    ongoing: 'தொடர்ச்சியான',
    months3_6: '3-6 மாதங்கள்',
    studentsAged16_25: '16-25 வயது மாணவர்கள்',
    farmersAgriEnthusiasts: 'விவசாயிகள் & விவசாய உத்வேகம்',
    allAgeGroups: 'அனைத்து வயது குழுக்கள்',
    youthAdults: 'இளைஞர்கள் & பெரியவர்கள்',
    womenGirls: 'பெண்கள் & சிறுமிகள்',
    extracurricular: 'பாடப்புத்தகத்திற்கு மேற்பட்ட நடவடிக்கைகள்',
    personalityDevelopment: 'ஆளுமை மேம்பாடு',
    sanitation: 'சுகாதாரம்',
    welfarePrograms: 'நலன்புரி திட்டங்கள்',
    environmentalConservation: 'சுற்றுச்சூழல் பாதுகாப்பு',
    soilTesting: 'மண் பரிசோதனை',
    ecologicalBalance: 'சூழலியல் சமநிலை',
    publicService: 'பொது சேவை',
    communityWelfare: 'சமூக நலன்',
    exploreDomain: 'களத்தை ஆராயுங்கள்',
    readMoreAboutUs: 'எங்களைப் பற்றி மேலும் அறிக',
    traditionalDance: 'பாரம்பரிய நடன நிகழ்ச்சி',
    studentScholarship: 'மாணவர் உதவித்தொகை விநியோகம்',
    freeHealthCheckup: 'இலவச ஆரோக்கிய பரிசோதனை முகாம்',
    communityMeeting: 'சமூக கூட்டம்',
    festivalCelebration: 'திருவிழா கொண்டாட்டம்',
    computerTraining: 'கணினி பயிற்சி அமர்வு',
    youthSports: 'இளைஞர் விளையாட்டு நிகழ்வு',
    musicProgram: 'இசை நிகழ்ச்சி',
    libraryInauguration: 'நூலக திறப்பு விழா',
    cleanlinessDrive: 'சுத்தம் இயக்கம்',
    interactiveMap: 'ஊடாடும் வரைபடம்',
    thankYouMessage: 'உங்கள் செய்திக்கு நன்றி! விரைவில் உங்களுக்கு பதிலளிப்போம்.',
    mapPlaceholder: 'வரைபட ஒருங்கிணைப்பு இங்கே இருக்கும்',
    exploreServices: 'சேவைகளை ஆராயுங்கள்',
    exploreGallery: 'கேலரியை ஆராயுங்கள்',
  viewFullGallery: "முழு கேலரியைக் காண்க",
  contactDescription: "எங்களைத் தொடர்பு கொள்ளுங்கள். உங்களுக்கு ஏதேனும் கேள்விகள் இருந்தால் உதவவும் பதிலளிக்கவும் நாங்கள் இங்கே உள்ளோம்.",
      title: 'எங்கள் YouTube சேனல்',
      description: 'எங்கள் சமூக நடவடிக்கைகளைப் பற்றி அறிந்துகொள்ள எங்கள் சமீபத்திய வீடியோக்களைப் பாருங்கள்',
      allVideos: 'அனைத்து வீடியோக்கள்',
      latest: 'சமீபத்திய',
      mostViewed: 'அதிகம் பார்க்கப்பட்டவை',
      events: 'நிகழ்வுகள்',
      new: 'புதிய',
      share: 'பகிர்',
      like: 'விரும்புகிறேன்',
      subscribers: 'சந்தாதாரர்கள்',
      videos: 'வீடியோக்கள்',
      youtubeTitle: "எங்கள் YouTube சேனல்",
  youtubeDescription: "எங்கள் சமூக செயல்பாடுகளுடன் புதிய வீடியோக்களைப் பார்த்து புதுப்பித்துக் கொள்ளுங்கள்",
      views: 'பார்வைகள்',
      years: 'ஆண்டுகள் உருவாக்குகிறது',
      ctaTitle: 'எங்கள் YouTube சேனலுக்கு சந்தா செலுத்துங்கள்',
      ctaDescription: 'எங்கள் சமீபத்திய சமூக நடவடிக்கைகள், நிகழ்வுகள் மற்றும் கல்வி உள்ளடக்கங்களைப் பற்றி அறிந்துகொள்ளுங்கள்',
      subscribeNow: 'இப்போது சந்தா செலுத்துங்கள்',
      loadMore: 'மேலும் வீடியோக்களை ஏற்றுக',
      exploreInitiatives: "எங்கள் முன்முயற்சிகளை ஆராயுங்கள்",
    exploreDomain: "துறையை ஆராயுங்கள்",
    readMoreAboutUs: "எங்களைப் பற்றி மேலும் அறிக",
    learnMore: "மேலும் அறிக",
  organizationFounded: "அமைப்பு நிறுவப்பட்டது",
  firstCommunityCenter: "முதல் சமூக மையம்",
  educationProgramLaunch: "கல்வி திட்டம் தொடக்கம்",
  digitalTransformation: "டிஜிட்டல் மாற்றம்",
  members500: "500+ உறுப்பினர்கள்",
  startedWith50Members: "50 உறுப்பினர்களுடன் தொடங்கப்பட்டது",
  establishedPermanentSpace: "நிரந்தர இடம் நிறுவப்பட்டது",
  scholarshipsForStudents: "மாணவர்களுக்கான உதவித்தொகை",
  onlineCommunityPlatform: "ஆன்லைன் சமூக தளம்",
  communityGrowthMilestone: "சமூக வளர்ச்சி மைல்கல்"
    
  },
  hi: {
    home: 'होम',
    about: 'हमारे बारे में',
    services: 'सेवाएं',
    gallery: 'गैलरी',
    events: 'कार्यक्रम',
    contact: 'संपर्क करें',
    heroTitle1: 'नल्लोर वट्टम में आपका स्वागत है',
    heroTitle2: 'सामाजिक विकास के लिए',
    heroTitle3: 'परंपरा को संरक्षित करना',
    heroSubtitle1: 'हमारे समुदाय की वृद्धि और प्रगति के लिए काम कर रहे हैं',
    heroSubtitle2: 'शिक्षा, स्वास्थ्य और सामाजिक विकास कार्यक्रम',
    heroSubtitle3: 'हमारी संस्कृति और विरासत की रक्षा करना',
    learnMore: 'अधिक जानें',
    getInvolved: 'हमसे जुड़ें',
    aboutTitle: 'नल्लोर वट्टम के बारे में',
    aboutText1: 'नल्लोर वट्टम हमारे क्षेत्र के सामाजिक, सांस्कृतिक और आर्थिक विकास के लिए समर्पित एक सामुदायिक संगठन है।',
    aboutText2: 'शिक्षा, स्वास्थ्य देखभाल पहल और सांस्कृतिक संरक्षण कार्यक्रमों के माध्यम से स्थायी विकास के अवसर पैदा करना हमारा मिशन है।',
    aboutText3: 'नल्लोर वट्टम हमारे क्षेत्र की सांस्कृतिक विरासत को बढ़ावा देने और संरक्षित करने के लिए समर्पित एक सामुदायिक संगठन है। 2005 में स्थापित, हम विभिन्न पृष्ठभूमि के लोगों को एक साथ ला रहे हैं ताकि हम अपनी साझा परंपराओं, मूल्यों और विरासत का जश्न मना सकें।',
    servicesTitle: 'हमारी सेवाएं',
    service1: 'छात्र डोमेन',
    service2: 'गांव डोमेन',
    service3: 'जीव विज्ञान डोमेन',
    service4: 'सरकारी डोमेन',
    service5: 'सेटिंग्स डोमेन',
    service6: 'महिला डोमेन',
    service7: 'युवा डोमेन',
    service8: 'विश्व डोमेन',
    service9: 'पर्यावरण डोमेन',
    service10: 'जागरूकता डोमेन',
    galleryTitle: 'हमारी गैलरी',
    eventsTitle: 'आगामी कार्यक्रम',
    event1: 'सांस्कृतिक उत्सव - 15 जनवरी, 2024',
    event2: 'स्वास्थ्य शिविर - 20 फरवरी, 2024',
    event3: 'शैक्षिक कार्यशाला - 10 मार्च, 2024',
    contactTitle: 'हमसे संपर्क करें',
    name: 'आपका नाम',
    email: 'आपका ईमेल',
    message: 'आपका संदेश',
    send: 'संदेश भेजें',
    footerDescription: 'नल्लोर वट्टम सामाजिक विकास और सांस्कृतिक संरक्षण के लिए काम करने वाला एक संगठन है।',
    quickLinks: 'त्वरित लिंक',
    contactInfo: 'संपर्क जानकारी',
    address: 'पेरियार पथ, चूलाइमेडु, चेन्नई-600094, तमिलनाडु, भारत',
    phone: '+91 98765 43210',
    emailAddress: 'info@nallorevattam.com',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    projectName: 'नल्लोर वट्टम',
    photoGallery: 'फोटो गैलरी',
    gallerySubtitle: 'हमारे समुदाय की यात्रा, उपलब्धियों और उत्सवों की दृश्य कहानियाँ',
    allPhotos: 'सभी फोटो',
    culturalEvents: 'सांस्कृतिक कार्यक्रम',
    education: 'शिक्षा',
    healthCamps: 'स्वास्थ्य शिविर',
    community: 'समुदाय',
    sendMessage: 'हमें एक संदेश भेजें',
    phoneNumber: 'फोन नंबर',
    subject: 'विषय',
    getInTouch: 'संपर्क में रहें',
    ourAddress: 'हमारा पता',
    workingHours: 'कार्य के घंटे',
    followUs: 'हमें फॉलो करें',
    contactSubtitle: 'हम आपसे सुनकर खुश होंगे। संपर्क करें और आइए एक बातचीत शुरू करें।',
    aboutNalloreVattam: 'नल्लोर वट्टम के बारे में',
    aboutSubtitle: 'एकता और विकास के माध्यम से मजबूत समुदाय का निर्माण',
    ourMission: 'हमारा मिशन',
    ourVision: 'हमारी दृष्टि',
    ourJourney: 'हमारी यात्रा',
    ourLeadershipTeam: 'हमारी नेतृत्व टीम',
    ourServices: 'हमारी सेवाएं',
    servicesSubtitle: 'सामुदायिक विकास कार्यक्रम',
    keyFeatures: 'मुख्य विशेषताएं',
    howItWorks: 'यह कैसे काम करता है',
    frequentlyAskedQuestions: 'अक्सर पूछे जाने वाले प्रश्न',
    register: 'पंजीकरण करें',
    apply: 'आवेदन करें',
    review: 'समीक्षा',
      president: "अध्यक्ष",
  secretary: "सचिव",
  treasurer: "कोषाध्यक्ष",
  presidentDesc: "10 वर्षों से अधिक समय से सामुदायिक पहलों का नेतृत्व कर रहे हैं",
  secretaryDesc: "महिला सशक्तिकरण कार्यक्रमों के लिए समर्पित",
  treasurerDesc: "वित्तीय प्रबंधन और संसाधन आवंटन",
    participate: 'भाग लें',
    learnMoreBtn: 'अधिक जानें',
    applyNow: 'अभी आवेदन करें',
    createAccount: 'अपना खाता बनाएं',
    chooseService: 'सेवा चुनें और आवेदन करें',
    teamReview: 'हमारी टीम आपके आवेदन की समीक्षा करती है',
    joinProgram: 'कार्यक्रम में शामिल हों और लाभ प्राप्त करें',
    faq1Question: 'शिक्षा छात्रवृत्ति के लिए आवेदन कैसे करें?',
    faq1Answer: 'आवेदन हर साल मई में स्वीकार किए जाते हैं। आवेदन पत्र और पात्रता मानदंडों के लिए हमारे कार्यालय या वेबसाइट पर जाएँ।',
    faq2Question: 'क्या स्वास्थ्य शिविर पूरी तरह से मुफ्त हैं?',
    faq2Answer: 'हां, हमारे सभी स्वास्थ्य शिविर मुफ्त मेडिकल चेकअप, बुनियादी दवाएं और स्वास्थ्य परामर्श प्रदान करते हैं।',
    faq3Question: 'कौशल विकास कार्यक्रमों के लिए पूर्व अनुभव की आवश्यकता है?',
    faq3Answer: 'किसी पूर्व अनुभव की आवश्यकता नहीं है। हमारे कार्यक्रम शुरुआती लोगों के लिए डिजाइन किए गए हैं और बुनियादी से उन्नत प्रशिक्षण शामिल है।',
    faq4Question: 'पंजीकरण के लिए कौन से दस्तावेज आवश्यक हैं?',
    faq4Answer: 'आपको पहचान प्रमाण, पता प्रमाण और आपके द्वारा आवेदन की जा रही सेवा के आधार पर प्रासंगिक शैक्षिक या पेशेवर प्रमाणपत्रों की आवश्यकता है।',
    faq5Question: 'आवेदन प्रक्रिया में कितना समय लगता है?',
    faq5Answer: 'आवेदन समीक्षा में आमतौर पर 2-3 सप्ताह लगते हैं। आपके आवेदन के संसाधित होने के बाद आपको ईमेल या फोन के माध्यम से सूचित किया जाएगा।',
    studentDomain: 'छात्र डोमेन',
    villageDomain: 'गांव डोमेन',
    domainOfBiology: 'जीव विज्ञान डोमेन',
    governmentDomain: 'सरकारी डोमेन',
    settingsDomain: 'सेटिंग्स डोमेन',
        learnMoreAboutUs: "हमारे बारे में और जानें",
youtubeTitle: "हमारा YouTube चैनल",
  youtubeDescription: "हमारे नवीनतम वीडियो देखें और हमारी सामुदायिक गतिविधियों के साथ अपडेट रहें",
    womensDomain: 'महिला डोमेन',
    youthDomain: 'युवा डोमेन',
    worldDomain: 'विश्व डोमेन',
    environmentalDomain: 'पर्यावरण डोमेन',
    awarenessDomain: 'जागरूकता डोमेन',
    studentDomainDesc: 'छात्रों के लिए व्यापक शैक्षिक सहायता और विकास कार्यक्रम। करियर मार्गदर्शन, छात्रवृत्ति और कौशल विकास पहल।',
    villageDomainDesc: 'गांव सुधार के लिए सामुदायिक विकास और ग्रामीण कल्याण कार्यक्रम। बुनियादी ढांचे का विकास और सामाजिक सेवा पहल।',
    domainOfBiologyDesc: 'सतत कृषि के लिए जैविक अनुसंधान और कृषि विकास। पर्यावरण अध्ययन और जैव विविधता संरक्षण कार्यक्रम।',
    governmentDomainDesc: 'सार्वजनिक कल्याण सेवाओं के लिए सरकारी अधिकारियों के साथ समन्वय। नीति कार्यान्वयन और नागरिक सगाई गतिविधियाँ।',
    settingsDomainDesc: 'संगठनात्मक संचालन के लिए तकनीकी कॉन्फ़िगरेशन और कार्यक्रम प्रबंधन। सिस्टम सपोर्ट और संसाधन समन्वय सेवाएं।',
    womensDomainDesc: 'महिला विकास के लिए सशक्तिकरण कार्यक्रम और सहायता सेवाएं। स्वयं सहायता समूह, स्वास्थ्य जागरूकता और आर्थिक स्वतंत्रता पहल।',
    youthDomainDesc: 'युवाओं के लिए युवा विकास कार्यक्रम और नेतृत्व प्रशिक्षण। करियर मार्गदर्शन, खेल और प्रतिभा विकास गतिविधियाँ।',
    worldDomainDesc: 'सामुदायिक विकास के लिए वैश्विक साझेदारी और अंतर्राष्ट्रीय सहयोग। सांस्कृतिक आदान-प्रदान और ज्ञान साझाकरण कार्यक्रम।',
    environmentalDomainDesc: 'हरित जीवन के लिए पर्यावरण संरक्षण और स्थिरता पहल। स्वच्छ ऊर्जा, अपशिष्ट प्रबंधन और संरक्षण कार्यक्रम।',
    awarenessDomainDesc: 'सामुदायिक ज्ञानोदय के लिए सार्वजनिक जागरूकता अभियान और शैक्षिक कार्यक्रम। सोशल मीडिया आउटरीच और कार्यशाला पहल।',
    educationalSupport: 'शैक्षिक सहायता',
    careerCounseling: 'करियर परामर्श',
    scholarshipPrograms: 'छात्रवृत्ति कार्यक्रम',
    skillDevelopment: 'कौशल विकास',
    communityDevelopment: 'सामुदायिक विकास',
    infrastructure: 'बुनियादी ढांचा',
    ruralWelfare: 'ग्रामीण कल्याण',
    socialServices: 'सामाजिक सेवाएं',
    agriculturalResearch: 'कृषि अनुसंधान',
    environmentalStudies: 'पर्यावरण अध्ययन',
    biodiversity: 'जैव विविधता',
    sustainableFarming: 'सतत कृषि',
    publicServices: 'सार्वजनिक सेवाएं',
    policyImplementation: 'नीति कार्यान्वयन',
    civicEngagement: 'नागरिक सगाई',
    communityOutreach: 'सामुदायिक आउटरीच',
    systemConfiguration: 'सिस्टम कॉन्फ़िगरेशन',
    technicalSupport: 'तकनीकी सहायता',
    programManagement: 'कार्यक्रम प्रबंधन',
    resourceCoordination: 'संसाधन समन्वय',
    womensEmpowerment: 'महिला सशक्तिकरण',
    selfHelpGroups: 'स्वयं सहायता समूह',
    healthAwareness: 'स्वास्थ्य जागरूकता',
    economicIndependence: 'आर्थिक स्वतंत्रता',
    youthLeadership: 'युवा नेतृत्व',
    sportsActivities: 'खेल गतिविधियाँ',
    talentDevelopment: 'प्रतिभा विकास',
    globalPartnerships: 'वैश्विक साझेदारी',
    culturalExchange: 'सांस्कृतिक आदान-प्रदान',
    internationalProjects: 'अंतर्राष्ट्रीय परियोजनाएं',
    knowledgeSharing: 'ज्ञान साझाकरण',
    environmentalProtection: 'पर्यावरण संरक्षण',
    cleanEnergy: 'स्वच्छ ऊर्जा',
    wasteManagement: 'अपशिष्ट प्रबंधन',
    greenInitiatives: 'हरित पहल',
    publicAwareness: 'सार्वजनिक जागरूकता',
    educationalCampaigns: 'शैक्षिक अभियान',
    socialMediaOutreach: 'सोशल मीडिया आउटरीच',
    communityWorkshops: 'सामुदायिक कार्यशालाएं',
    academicYear: 'शैक्षणिक वर्ष',
    continuous: 'निरंतर',
    studentsAllAges: 'सभी उम्र के छात्र',
    allVillagers: 'सभी ग्रामीण',
    farmersResearchers: 'किसान और शोधकर्ता',
    allCitizens: 'सभी नागरिक',
    authorizedPersonnel: 'अधिकृत कर्मियों',
    womenAllAges: 'सभी उम्र की महिलाएं',
    youth15_30: 'युवा 15-30 वर्ष',
    allMembers: 'सभी सदस्य',
    allCommunityMembers: 'सभी सामुदायिक सदस्य',
    generalPublic: 'सामान्य जनता',
    missionDescription: 'शिक्षा, सांस्कृतिक संरक्षण और सतत विकास पहलों के माध्यम से हमारे समुदाय को सशक्त बनाना जो स्थायी सकारात्मक प्रभाव पैदा करते हैं।',
    visionDescription: 'एक आत्मनिर्भर, सांस्कृतिक रूप से समृद्ध समुदाय जहां हर सदस्य के पास विकास, शिक्षा और समृद्धि के अवसर हैं।',
    tuitionFeeSupport: 'ट्यूशन फीस सहायता',
    bookAllowance: 'पुस्तक भत्ता',
    mentorshipProgram: 'मेंटरशिप कार्यक्रम',
    careerGuidance: 'करियर मार्गदर्शन',
    generalCheckup: 'सामान्य जांच',
    dentalCare: 'दंत देखभाल',
    eyeTesting: 'आंखों की जांच',
    healthAwareness: 'स्वास्थ्य जागरूकता',
    organicFarming: 'जैविक खेती',
    waterManagement: 'जल प्रबंधन',
    contactUs: "हमसे संपर्क करें",

    cropRotation: 'फसल चक्र',
    marketLinkages: 'बाजार संबंध',
    festivalCelebrations: 'त्योहार समारोह',
    traditionalArts: 'पारंपरिक कलाएं',
    musicDance: 'संगीत और नृत्य',
    heritageWorkshops: 'विरासत कार्यशालाएं',
    computerSkills: 'कंप्यूटर कौशल',
    handicrafts: 'हस्तशिल्प',
    technicalTraining: 'तकनीकी प्रशिक्षण',
    softSkills: 'सॉफ्ट स्किल्स',
    businessTraining: 'व्यवसाय प्रशिक्षण',
    legalAwareness: 'कानूनी जागरूकता',
    healthPrograms: 'स्वास्थ्य कार्यक्रम',
    annual: 'वार्षिक',
    quarterly: 'त्रैमासिक',
    seasonal: 'मौसमी',
    monthly: 'मासिक',
    ongoing: 'चल रहा',
    months3_6: '3-6 महीने',
    studentsAged16_25: '16-25 वर्ष की आयु के छात्र',
    farmersAgriEnthusiasts: 'किसान और कृषि उत्साही',
    allAgeGroups: 'सभी आयु वर्ग',
    youthAdults: 'युवा और वयस्क',
    womenGirls: 'महिलाएं और लड़कियां',
    extracurricular: 'पाठ्येतर गतिविधियां',
    personalityDevelopment: 'व्यक्तित्व विकास',
    sanitation: 'स्वच्छता',
    welfarePrograms: 'कल्याण कार्यक्रम',
    environmentalConservation: 'पर्यावरण संरक्षण',
    soilTesting: 'मृदा परीक्षण',
    ecologicalBalance: 'पारिस्थितिक संतुलन',
    publicService: 'सार्वजनिक सेवा',
    communityWelfare: 'सामुदायिक कल्याण',
    exploreDomain: 'डोमेन एक्सप्लोर करें',
    readMoreAboutUs: 'हमारे बारे में और पढ़ें',
    traditionalDance: 'पारंपरिक नृत्य प्रदर्शन',
    studentScholarship: 'छात्रवृत्ति वितरण',
    freeHealthCheckup: 'मुफ्त स्वास्थ्य जांच शिविर',
    communityMeeting: 'सामुदायिक बैठक',
    festivalCelebration: 'त्योहार समारोह',
    computerTraining: 'कंप्यूटर प्रशिक्षण सत्र',
    youthSports: 'युवा खेल आयोजन',
    musicProgram: 'संगीत कार्यक्रम',
    libraryInauguration: 'पुस्तकालय उद्घाटन',
    cleanlinessDrive: 'स्वच्छता अभियान',
    interactiveMap: 'इंटरएक्टिव मानचित्र',
    thankYouMessage: 'आपके संदेश के लिए धन्यवाद! हम जल्द ही आपको वापस संपर्क करेंगे।',
    mapPlaceholder: 'मानचित्र एकीकरण यहां होगा',
    exploreServices: 'सेवाओं का अन्वेषण करें',
    exploreGallery: 'गैलरी का अन्वेषण करें',
  viewAllServices: "सभी सेवाएं देखें",
  viewFullGallery:'पूरी गैलरी देखें' ,

  galleryDescription: "सामुदायिक विकास, सांस्कृतिक उत्सव और सार्थक संवाद के पलों को कैद करना",
  contactDescription: "हमसे संपर्क करें। हम आपकी मदद करने और आपके किसी भी प्रश्न का उत्तर देने के लिए यहां हैं।",

      title: 'हमारा YouTube चैनल',
      description: 'हमारे नवीनतम वीडियो देखें और हमारे सामुदायिक गतिविधियों से अपडेट रहें',
      allVideos: 'सभी वीडियो',
      latest: 'नवीनतम',
      mostViewed: 'सबसे ज्यादा देखे गए',
      events: 'कार्यक्रम',
      new: 'नया',
      share: 'साझा करें',
      like: 'पसंद',
      subscribers: 'सब्सक्राइबर्स',
      videos: 'वीडियो',
      views: 'व्यूज',
      years: 'वर्षों से बना रहे',
      ctaTitle: 'हमारे YouTube चैनल को सब्सक्राइब करें',
      ctaDescription: 'हमारी नवीनतम सामुदायिक गतिविधियों, कार्यक्रमों और शैक्षिक सामग्री से अपडेट रहें',
      subscribeNow: 'अभी सब्सक्राइब करें',
      loadMore: 'और वीडियो लोड करें',
      exploreInitiatives: "हमारी पहलों को देखें",
    exploreDomain: "डोमेन देखें",
    readMoreAboutUs: "हमारे बारे में और पढ़ें",
    learnMore: "और जानें",
  organizationFounded: "संगठन की स्थापना",
  firstCommunityCenter: "पहला सामुदायिक केंद्र",
  educationProgramLaunch: "शिक्षा कार्यक्रम शुरू",
  digitalTransformation: "डिजिटल परिवर्तन",
  members500: "500+ सदस्य",
  startedWith50Members: "50 सदस्यों के साथ शुरू",
  establishedPermanentSpace: "स्थायी स्थान स्थापित",
  scholarshipsForStudents: "छात्रों के लिए छात्रवृत्ति",
  onlineCommunityPlatform: "ऑनलाइन सामुदायिक प्लेटफॉर्म",
  communityGrowthMilestone: "सामुदायिक विकास मील का पत्थर"

    
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentPage, setCurrentPage] = useState("home");
  const [currentLanguage, setCurrentLanguage] = useState("ta"); // Tamil as default

  // Simple translation function - NO API calls
  const t = (text) => {
    return translations[currentLanguage]?.[text] || translations.en[text] || text;
  };

  // Simple translateContent function - NO API calls
  const translateContent = async (jsonContent) => {
    if (currentLanguage === "en") return jsonContent;
    
    const translatedContent = { ...jsonContent };
    
    for (const key of Object.keys(jsonContent)) {
      const value = jsonContent[key];
      if (typeof value === "string") {
        // Use pre-loaded translations directly
        translatedContent[key] = translations[currentLanguage]?.[value] || value;
      }
    }
    
    return translatedContent;
  };

  const isTranslating = false;

  return (
    <LanguageContext.Provider
      value={{
        currentPage,
        setCurrentPage,
        currentLanguage,
        setCurrentLanguage,
        supportedLanguages,
        t,
        translateContent,
        isTranslating,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

// ✅ MAKE SURE THIS EXPORT EXISTS
export const useLanguage = () => useContext(LanguageContext);